server:
  port: 8080
app:
  test: 123
  token: "6133356316:AAFyhfdTvsoMIs7-dNiQ_C0VmD26TpclO7Y"
springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui